# Basic
title: Eirc 楚鸿
subtitle: 天行健，君子以自强不息
welcome_message: <a href="https://github.com/ericchuhong" target="_blank">比起别人要做成一件事我要花费两倍的时间呢，慢慢来</a>
description: Hi！我是马楚鸿，一个iOS入门开发者，喜欢一切有趣的事物，正在沉淀着自己的人生.
creator: <a href="https://github.com/ericchuhong">@eric</a>

url: "http://www.ericchuhong.com/"

permalink: /:year/:month/:title/

# Format
highlighter: plain
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 查看博客

# Navigation buttons in the front page.
nav:
    - {title: 我的项目, description: My Projects, url: 'https://github.com/ericchuhong'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: eric
    github: eric
    twitter: eric
    gplus: 107108267983477358170
    mail: ericchuhong@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
